// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ChangeRecord;
@class ChatCacheCookie;
@class ChatCookieData;
@class ChatMessage;
@class ChatSession;
@class FriendInfo;
@class GcmData;
@class Group;
@class GroupInfo;
@class GroupMember;
@class IMTransferData;
@class MessageData;
@class OfflineMsg;
@class ProducerMsgDetail;
@class RelationShip;
@class Reviewed;
@class UserCommonGroups;
@class UserInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ChatType

/** 聊天类型 */
typedef GPB_ENUM(ChatType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ChatType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 个人聊天 */
  ChatType_Private = 0,

  /** 群组聊天 */
  ChatType_Groupchat = 1,

  /** Connect */
  ChatType_ConnectSystem = 2,
};

GPBEnumDescriptor *ChatType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ChatType_IsValidValue(int32_t value);

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - NewConnection

typedef GPB_ENUM(NewConnection_FieldNumber) {
  NewConnection_FieldNumber_Salt = 1,
  NewConnection_FieldNumber_PubKey = 2,
};

/**
 * socket
 **/
@interface NewConnection : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *salt;

@property(nonatomic, readwrite, copy, null_resettable) NSData *pubKey;

@end

#pragma mark - IMRequest

typedef GPB_ENUM(IMRequest_FieldNumber) {
  IMRequest_FieldNumber_PubKey = 1,
  IMRequest_FieldNumber_Sign = 2,
  IMRequest_FieldNumber_CipherData = 3,
};

@interface IMRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, strong, null_resettable) GcmData *cipherData;
/** Test to see if @c cipherData has been set. */
@property(nonatomic, readwrite) BOOL hasCipherData;

@end

#pragma mark - DeviceInfo

typedef GPB_ENUM(DeviceInfo_FieldNumber) {
  DeviceInfo_FieldNumber_DeviceId = 1,
  DeviceInfo_FieldNumber_DeviceName = 2,
  DeviceInfo_FieldNumber_Locale = 3,
  DeviceInfo_FieldNumber_Cv = 4,
  DeviceInfo_FieldNumber_Uuid = 5,
  DeviceInfo_FieldNumber_ChatCookieData = 6,
};

@interface DeviceInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

@property(nonatomic, readwrite) int32_t cv;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, strong, null_resettable) ChatCookieData *chatCookieData;
/** Test to see if @c chatCookieData has been set. */
@property(nonatomic, readwrite) BOOL hasChatCookieData;

@end

#pragma mark - RemoveRelationship

typedef GPB_ENUM(RemoveRelationship_FieldNumber) {
  RemoveRelationship_FieldNumber_Uid = 1,
};

@interface RemoveRelationship : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - SettingFriendInfo

typedef GPB_ENUM(SettingFriendInfo_FieldNumber) {
  SettingFriendInfo_FieldNumber_Uid = 1,
  SettingFriendInfo_FieldNumber_Remark = 2,
  SettingFriendInfo_FieldNumber_Common = 3,
};

@interface SettingFriendInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

@property(nonatomic, readwrite) BOOL common;

@end

#pragma mark - AddFriendRequest

typedef GPB_ENUM(AddFriendRequest_FieldNumber) {
  AddFriendRequest_FieldNumber_Uid = 1,
  AddFriendRequest_FieldNumber_Tips = 2,
  AddFriendRequest_FieldNumber_Source = 3,
};

@interface AddFriendRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite) int32_t source;

@end

#pragma mark - ExternalBillingToken

typedef GPB_ENUM(ExternalBillingToken_FieldNumber) {
  ExternalBillingToken_FieldNumber_Token = 1,
};

@interface ExternalBillingToken : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - RedPackageToken

typedef GPB_ENUM(RedPackageToken_FieldNumber) {
  RedPackageToken_FieldNumber_Token = 1,
};

@interface RedPackageToken : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - SyncRelationship

typedef GPB_ENUM(SyncRelationship_FieldNumber) {
  SyncRelationship_FieldNumber_Version = 1,
};

@interface SyncRelationship : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@end

#pragma mark - AcceptFriendRequest

typedef GPB_ENUM(AcceptFriendRequest_FieldNumber) {
  AcceptFriendRequest_FieldNumber_Uid = 1,
  AcceptFriendRequest_FieldNumber_Source = 2,
};

@interface AcceptFriendRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite) int32_t source;

@end

#pragma mark - FriendChatCookie

typedef GPB_ENUM(FriendChatCookie_FieldNumber) {
  FriendChatCookie_FieldNumber_Uid = 1,
  FriendChatCookie_FieldNumber_Pubkey = 2,
};

@interface FriendChatCookie : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubkey;

@end

#pragma mark - FriendInfo

typedef GPB_ENUM(FriendInfo_FieldNumber) {
  FriendInfo_FieldNumber_Username = 1,
  FriendInfo_FieldNumber_Avatar = 2,
  FriendInfo_FieldNumber_PubKey = 3,
  FriendInfo_FieldNumber_Uid = 4,
  FriendInfo_FieldNumber_Common = 5,
  FriendInfo_FieldNumber_Source = 6,
  FriendInfo_FieldNumber_Remark = 7,
  FriendInfo_FieldNumber_ConnectId = 8,
};

@interface FriendInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite) BOOL common;

@property(nonatomic, readwrite) int32_t source;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectId;

@end

#pragma mark - RelationShip

typedef GPB_ENUM(RelationShip_FieldNumber) {
  RelationShip_FieldNumber_Version = 1,
  RelationShip_FieldNumber_FriendsArray = 2,
};

@interface RelationShip : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FriendInfo*> *friendsArray;
/** The number of items in @c friendsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger friendsArray_Count;

@end

#pragma mark - UserCommonGroups

typedef GPB_ENUM(UserCommonGroups_FieldNumber) {
  UserCommonGroups_FieldNumber_GroupsArray = 1,
};

@interface UserCommonGroups : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupInfo*> *groupsArray;
/** The number of items in @c groupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupsArray_Count;

@end

#pragma mark - GroupMember

typedef GPB_ENUM(GroupMember_FieldNumber) {
  GroupMember_FieldNumber_Username = 1,
  GroupMember_FieldNumber_Avatar = 2,
  GroupMember_FieldNumber_Uid = 3,
  GroupMember_FieldNumber_Role = 4,
  GroupMember_FieldNumber_Nick = 5,
  GroupMember_FieldNumber_PubKey = 6,
  GroupMember_FieldNumber_ConnectId = 7,
};

@interface GroupMember : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite) int32_t role;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nick;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectId;

@end

#pragma mark - Group

typedef GPB_ENUM(Group_FieldNumber) {
  Group_FieldNumber_Identifier = 1,
  Group_FieldNumber_Name = 2,
  Group_FieldNumber_Summary = 3,
  Group_FieldNumber_Public_p = 4,
  Group_FieldNumber_Reviewed = 5,
  Group_FieldNumber_Avatar = 6,
};

@interface Group : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *identifier;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *summary;

@property(nonatomic, readwrite) BOOL public_p;

@property(nonatomic, readwrite) BOOL reviewed;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - GroupInfo

typedef GPB_ENUM(GroupInfo_FieldNumber) {
  GroupInfo_FieldNumber_Group = 1,
  GroupInfo_FieldNumber_MembersArray = 2,
  GroupInfo_FieldNumber_Backup = 3,
  GroupInfo_FieldNumber_Ecdh = 4,
};

@interface GroupInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Group *group;
/** Test to see if @c group has been set. */
@property(nonatomic, readwrite) BOOL hasGroup;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GroupMember*> *membersArray;
/** The number of items in @c membersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger membersArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *backup;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ecdh;

@end

#pragma mark - SyncUserRelationship

typedef GPB_ENUM(SyncUserRelationship_FieldNumber) {
  SyncUserRelationship_FieldNumber_RelationShip = 1,
  SyncUserRelationship_FieldNumber_UserCommonGroups = 2,
};

@interface SyncUserRelationship : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RelationShip *relationShip;
/** Test to see if @c relationShip has been set. */
@property(nonatomic, readwrite) BOOL hasRelationShip;

@property(nonatomic, readwrite, strong, null_resettable) UserCommonGroups *userCommonGroups;
/** Test to see if @c userCommonGroups has been set. */
@property(nonatomic, readwrite) BOOL hasUserCommonGroups;

@end

#pragma mark - SyncBadge

typedef GPB_ENUM(SyncBadge_FieldNumber) {
  SyncBadge_FieldNumber_Badge = 1,
};

@interface SyncBadge : GPBMessage

@property(nonatomic, readwrite) int32_t badge;

@end

#pragma mark - NOInterest

typedef GPB_ENUM(NOInterest_FieldNumber) {
  NOInterest_FieldNumber_Uid = 1,
};

@interface NOInterest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - DeviceToken

typedef GPB_ENUM(DeviceToken_FieldNumber) {
  DeviceToken_FieldNumber_ApnsDeviceToken = 1,
  DeviceToken_FieldNumber_XgDeviceToken = 2,
  DeviceToken_FieldNumber_GcmDeviceToken = 3,
  DeviceToken_FieldNumber_PushType = 4,
  DeviceToken_FieldNumber_DeviceId = 5,
  DeviceToken_FieldNumber_Locale = 6,
};

@interface DeviceToken : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *apnsDeviceToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *xgDeviceToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gcmDeviceToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pushType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

@end

#pragma mark - UpdateSession

typedef GPB_ENUM(UpdateSession_FieldNumber) {
  UpdateSession_FieldNumber_Uid = 1,
  UpdateSession_FieldNumber_Mute = 2,
};

@interface UpdateSession : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite) BOOL mute;

@end

#pragma mark - CommandMessage

typedef GPB_ENUM(CommandMessage_FieldNumber) {
  CommandMessage_FieldNumber_CommandId = 1,
  CommandMessage_FieldNumber_CommandExtension = 2,
  CommandMessage_FieldNumber_TransferData = 3,
  CommandMessage_FieldNumber_CookieData = 4,
  CommandMessage_FieldNumber_ChatCookie = 5,
};

@interface CommandMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *commandId;

@property(nonatomic, readwrite) int32_t commandExtension;

@property(nonatomic, readwrite, strong, null_resettable) IMTransferData *transferData;
/** Test to see if @c transferData has been set. */
@property(nonatomic, readwrite) BOOL hasTransferData;

/** 上传chatcookie使用 */
@property(nonatomic, readwrite, strong, null_resettable) ChatCookieData *cookieData;
/** Test to see if @c cookieData has been set. */
@property(nonatomic, readwrite) BOOL hasCookieData;

/** 上传chatcookie使用 */
@property(nonatomic, readwrite, strong, null_resettable) ChatCacheCookie *chatCookie;
/** Test to see if @c chatCookie has been set. */
@property(nonatomic, readwrite) BOOL hasChatCookie;

@end

#pragma mark - MessageDidRead

typedef GPB_ENUM(MessageDidRead_FieldNumber) {
  MessageDidRead_FieldNumber_MsgId = 1,
  MessageDidRead_FieldNumber_MsgOwer = 2,
};

@interface MessageDidRead : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgOwer;

@end

#pragma mark - CommandStauts

typedef GPB_ENUM(CommandStauts_FieldNumber) {
  CommandStauts_FieldNumber_Status = 1,
};

@interface CommandStauts : GPBMessage

@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - ReceiveFriendRequest

typedef GPB_ENUM(ReceiveFriendRequest_FieldNumber) {
  ReceiveFriendRequest_FieldNumber_Sender = 1,
  ReceiveFriendRequest_FieldNumber_Tips = 2,
  ReceiveFriendRequest_FieldNumber_Source = 3,
};

@interface ReceiveFriendRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *sender;
/** Test to see if @c sender has been set. */
@property(nonatomic, readwrite) BOOL hasSender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite) int32_t source;

@end

#pragma mark - ChangeRecords

typedef GPB_ENUM(ChangeRecords_FieldNumber) {
  ChangeRecords_FieldNumber_Version = 1,
  ChangeRecords_FieldNumber_ChangeRecordsArray = 2,
};

@interface ChangeRecords : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ChangeRecord*> *changeRecordsArray;
/** The number of items in @c changeRecordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger changeRecordsArray_Count;

@end

#pragma mark - ChangeRecord

typedef GPB_ENUM(ChangeRecord_FieldNumber) {
  ChangeRecord_FieldNumber_Category = 1,
  ChangeRecord_FieldNumber_UserInfo = 2,
};

@interface ChangeRecord : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *category;

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@end

#pragma mark - FriendListChange

typedef GPB_ENUM(FriendListChange_FieldNumber) {
  FriendListChange_FieldNumber_Change = 1,
  FriendListChange_FieldNumber_Version = 2,
};

@interface FriendListChange : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ChangeRecord *change;
/** Test to see if @c change has been set. */
@property(nonatomic, readwrite) BOOL hasChange;

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@end

#pragma mark - ExternalRedPackageInfo

typedef GPB_ENUM(ExternalRedPackageInfo_FieldNumber) {
  ExternalRedPackageInfo_FieldNumber_HashId = 1,
  ExternalRedPackageInfo_FieldNumber_Sender = 2,
  ExternalRedPackageInfo_FieldNumber_Tips = 3,
  ExternalRedPackageInfo_FieldNumber_MsgId = 4,
  ExternalRedPackageInfo_FieldNumber_System = 5,
};

@interface ExternalRedPackageInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *sender;
/** Test to see if @c sender has been set. */
@property(nonatomic, readwrite) BOOL hasSender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) BOOL system;

@end

#pragma mark - GroupChange

typedef GPB_ENUM(GroupChange_FieldNumber) {
  GroupChange_FieldNumber_Identifier = 1,
  GroupChange_FieldNumber_ChangeType = 2,
  GroupChange_FieldNumber_Detail = 3,
  GroupChange_FieldNumber_Count = 4,
  GroupChange_FieldNumber_InviteBy = 5,
};

/**
 * socket
 **/
@interface GroupChange : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *identifier;

@property(nonatomic, readwrite) int32_t changeType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *detail;

@property(nonatomic, readwrite) int32_t count;

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *inviteBy;
/** Test to see if @c inviteBy has been set. */
@property(nonatomic, readwrite) BOOL hasInviteBy;

@end

#pragma mark - UserInfo

typedef GPB_ENUM(UserInfo_FieldNumber) {
  UserInfo_FieldNumber_Username = 1,
  UserInfo_FieldNumber_Avatar = 2,
  UserInfo_FieldNumber_PubKey = 3,
  UserInfo_FieldNumber_Uid = 4,
  UserInfo_FieldNumber_Recommend = 5,
  UserInfo_FieldNumber_ConnectId = 6,
  UserInfo_FieldNumber_Source = 7,
  UserInfo_FieldNumber_CreatedAt = 8,
  UserInfo_FieldNumber_UpdateConnectId = 9,
};

@interface UserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite) BOOL recommend;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectId;

@property(nonatomic, readwrite) int32_t source;

@property(nonatomic, readwrite) int64_t createdAt;

@property(nonatomic, readwrite) BOOL updateConnectId;

@end

#pragma mark - ProducerMsgDetail

typedef GPB_ENUM(ProducerMsgDetail_FieldNumber) {
  ProducerMsgDetail_FieldNumber_Type = 1,
  ProducerMsgDetail_FieldNumber_Ext = 2,
  ProducerMsgDetail_FieldNumber_Data_p = 3,
};

@interface ProducerMsgDetail : GPBMessage

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) int32_t ext;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - QuitMessage

typedef GPB_ENUM(QuitMessage_FieldNumber) {
  QuitMessage_FieldNumber_DeviceName = 1,
};

@interface QuitMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@end

#pragma mark - IMResponse

typedef GPB_ENUM(IMResponse_FieldNumber) {
  IMResponse_FieldNumber_Sign = 1,
  IMResponse_FieldNumber_CipherData = 2,
};

@interface IMResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, strong, null_resettable) GcmData *cipherData;
/** Test to see if @c cipherData has been set. */
@property(nonatomic, readwrite) BOOL hasCipherData;

@end

#pragma mark - OfflineMsg

typedef GPB_ENUM(OfflineMsg_FieldNumber) {
  OfflineMsg_FieldNumber_MsgId = 1,
  OfflineMsg_FieldNumber_Body = 2,
};

@interface OfflineMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, strong, null_resettable) ProducerMsgDetail *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - OfflineMsgs

typedef GPB_ENUM(OfflineMsgs_FieldNumber) {
  OfflineMsgs_FieldNumber_OfflineMsgsArray = 1,
  OfflineMsgs_FieldNumber_Completed = 2,
};

@interface OfflineMsgs : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OfflineMsg*> *offlineMsgsArray;
/** The number of items in @c offlineMsgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger offlineMsgsArray_Count;

@property(nonatomic, readwrite) BOOL completed;

@end

#pragma mark - NoticeMessage

typedef GPB_ENUM(NoticeMessage_FieldNumber) {
  NoticeMessage_FieldNumber_Category = 1,
  NoticeMessage_FieldNumber_Body = 2,
  NoticeMessage_FieldNumber_MsgId = 3,
};

@interface NoticeMessage : GPBMessage

@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite, copy, null_resettable) NSData *body;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@end

#pragma mark - GcmData

typedef GPB_ENUM(GcmData_FieldNumber) {
  GcmData_FieldNumber_Iv = 1,
  GcmData_FieldNumber_Aad = 2,
  GcmData_FieldNumber_Tag = 3,
  GcmData_FieldNumber_Ciphertext = 4,
};

/**
 * Aes GCM 密文
 **/
@interface GcmData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *iv;

@property(nonatomic, readwrite, copy, null_resettable) NSData *aad;

@property(nonatomic, readwrite, copy, null_resettable) NSData *tag;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ciphertext;

@end

#pragma mark - IMTransferData

typedef GPB_ENUM(IMTransferData_FieldNumber) {
  IMTransferData_FieldNumber_Sign = 1,
  IMTransferData_FieldNumber_CipherData = 2,
};

@interface IMTransferData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, strong, null_resettable) GcmData *cipherData;
/** Test to see if @c cipherData has been set. */
@property(nonatomic, readwrite) BOOL hasCipherData;

@end

#pragma mark - Command

typedef GPB_ENUM(Command_FieldNumber) {
  Command_FieldNumber_MsgId = 1,
  Command_FieldNumber_Detail = 2,
  Command_FieldNumber_ErrNo = 3,
  Command_FieldNumber_Msg = 4,
};

@interface Command : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *detail;

@property(nonatomic, readwrite) int32_t errNo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@end

#pragma mark - RichMedia

typedef GPB_ENUM(RichMedia_FieldNumber) {
  RichMedia_FieldNumber_Thumbnail = 1,
  RichMedia_FieldNumber_Entity = 2,
};

@interface RichMedia : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *thumbnail;

@property(nonatomic, readwrite, copy, null_resettable) NSData *entity;

@end

#pragma mark - MediaFile

typedef GPB_ENUM(MediaFile_FieldNumber) {
  MediaFile_FieldNumber_PubKey = 1,
  MediaFile_FieldNumber_Sign = 2,
  MediaFile_FieldNumber_CipherData = 3,
};

@interface MediaFile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, strong, null_resettable) GcmData *cipherData;
/** Test to see if @c cipherData has been set. */
@property(nonatomic, readwrite) BOOL hasCipherData;

@end

#pragma mark - StructData

typedef GPB_ENUM(StructData_FieldNumber) {
  StructData_FieldNumber_Random = 1,
  StructData_FieldNumber_PlainData = 2,
};

@interface StructData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *random;

@property(nonatomic, readwrite, copy, null_resettable) NSData *plainData;

@end

#pragma mark - MessagePost

typedef GPB_ENUM(MessagePost_FieldNumber) {
  MessagePost_FieldNumber_PubKey = 1,
  MessagePost_FieldNumber_Sign = 2,
  MessagePost_FieldNumber_MsgData = 3,
};

@interface MessagePost : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, strong, null_resettable) MessageData *msgData;
/** Test to see if @c msgData has been set. */
@property(nonatomic, readwrite) BOOL hasMsgData;

@end

#pragma mark - Reviewed

typedef GPB_ENUM(Reviewed_FieldNumber) {
  Reviewed_FieldNumber_Category = 1,
  Reviewed_FieldNumber_Identifier = 2,
  Reviewed_FieldNumber_Tips = 3,
  Reviewed_FieldNumber_UserInfo = 4,
  Reviewed_FieldNumber_VerificationCode = 5,
  Reviewed_FieldNumber_Source = 6,
  Reviewed_FieldNumber_Name = 7,
};

@interface Reviewed : GPBMessage

@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite, copy, null_resettable) NSString *identifier;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *verificationCode;

@property(nonatomic, readwrite) int32_t source;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - ReviewedStatus

typedef GPB_ENUM(ReviewedStatus_FieldNumber) {
  ReviewedStatus_FieldNumber_Review = 1,
  ReviewedStatus_FieldNumber_Refused = 2,
  ReviewedStatus_FieldNumber_Newaccept = 3,
};

@interface ReviewedStatus : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Reviewed *review;
/** Test to see if @c review has been set. */
@property(nonatomic, readwrite) BOOL hasReview;

@property(nonatomic, readwrite) BOOL refused;

@property(nonatomic, readwrite) BOOL newaccept;

@end

#pragma mark - SystemRedPackage

typedef GPB_ENUM(SystemRedPackage_FieldNumber) {
  SystemRedPackage_FieldNumber_Amount = 1,
  SystemRedPackage_FieldNumber_HashId = 2,
  SystemRedPackage_FieldNumber_Tips = 3,
};

@interface SystemRedPackage : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - UpdateMobileBind

typedef GPB_ENUM(UpdateMobileBind_FieldNumber) {
  UpdateMobileBind_FieldNumber_Username = 1,
};

@interface UpdateMobileBind : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@end

#pragma mark - AddressNotify

typedef GPB_ENUM(AddressNotify_FieldNumber) {
  AddressNotify_FieldNumber_TxId = 1,
  AddressNotify_FieldNumber_Amount = 2,
};

@interface AddressNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *txId;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - RemoveGroup

typedef GPB_ENUM(RemoveGroup_FieldNumber) {
  RemoveGroup_FieldNumber_Name = 1,
  RemoveGroup_FieldNumber_GroupId = 2,
};

@interface RemoveGroup : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - Announcement

typedef GPB_ENUM(Announcement_FieldNumber) {
  Announcement_FieldNumber_CreatedAt = 1,
  Announcement_FieldNumber_Title = 2,
  Announcement_FieldNumber_Content = 3,
  Announcement_FieldNumber_URL = 4,
  Announcement_FieldNumber_Category = 5,
  Announcement_FieldNumber_Desc = 6,
  Announcement_FieldNumber_CoversURL = 7,
  Announcement_FieldNumber_Version = 8,
};

@interface Announcement : GPBMessage

@property(nonatomic, readwrite) float createdAt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

@property(nonatomic, readwrite, copy, null_resettable) NSString *coversURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@end

#pragma mark - SystemRedpackgeNotice

typedef GPB_ENUM(SystemRedpackgeNotice_FieldNumber) {
  SystemRedpackgeNotice_FieldNumber_Receiver = 1,
  SystemRedpackgeNotice_FieldNumber_Amount = 2,
  SystemRedpackgeNotice_FieldNumber_Hashid = 3,
};

@interface SystemRedpackgeNotice : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserInfo *receiver;
/** Test to see if @c receiver has been set. */
@property(nonatomic, readwrite) BOOL hasReceiver;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashid;

@end

#pragma mark - ReviewedResponse

typedef GPB_ENUM(ReviewedResponse_FieldNumber) {
  ReviewedResponse_FieldNumber_Category = 1,
  ReviewedResponse_FieldNumber_Identifier = 2,
  ReviewedResponse_FieldNumber_Name = 3,
  ReviewedResponse_FieldNumber_Success = 4,
};

@interface ReviewedResponse : GPBMessage

@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite, copy, null_resettable) NSString *identifier;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) BOOL success;

@end

#pragma mark - GroupApplyChange

typedef GPB_ENUM(GroupApplyChange_FieldNumber) {
  GroupApplyChange_FieldNumber_VerificationCode = 1,
  GroupApplyChange_FieldNumber_Tips = 2,
  GroupApplyChange_FieldNumber_Source = 3,
  GroupApplyChange_FieldNumber_TipsHistoryArray = 4,
};

@interface GroupApplyChange : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *verificationCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite) int32_t source;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tipsHistoryArray;
/** The number of items in @c tipsHistoryArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tipsHistoryArray_Count;

@end

#pragma mark - SystemTransferPackage

typedef GPB_ENUM(SystemTransferPackage_FieldNumber) {
  SystemTransferPackage_FieldNumber_Amount = 1,
  SystemTransferPackage_FieldNumber_Txid = 2,
  SystemTransferPackage_FieldNumber_Tips = 3,
  SystemTransferPackage_FieldNumber_Sender = 4,
};

@interface SystemTransferPackage : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *txid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@end

#pragma mark - MSMessage

typedef GPB_ENUM(MSMessage_FieldNumber) {
  MSMessage_FieldNumber_MsgId = 1,
  MSMessage_FieldNumber_Body = 2,
  MSMessage_FieldNumber_Category = 3,
};

/**
 * 系统消息
 **/
@interface MSMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *body;

@property(nonatomic, readwrite) int32_t category;

@end

#pragma mark - RejectMessage

typedef GPB_ENUM(RejectMessage_FieldNumber) {
  RejectMessage_FieldNumber_MsgId = 1,
  RejectMessage_FieldNumber_Uid = 2,
  RejectMessage_FieldNumber_Status = 3,
  RejectMessage_FieldNumber_Data_p = 4,
};

@interface RejectMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - ChatCacheCookie

typedef GPB_ENUM(ChatCacheCookie_FieldNumber) {
  ChatCacheCookie_FieldNumber_ChatPubKey = 1,
  ChatCacheCookie_FieldNumber_Salt = 2,
  ChatCacheCookie_FieldNumber_ChatPrivkey = 3,
};

@interface ChatCacheCookie : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatPubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSData *salt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatPrivkey;

@end

#pragma mark - CreateGroupMessage

typedef GPB_ENUM(CreateGroupMessage_FieldNumber) {
  CreateGroupMessage_FieldNumber_Identifier = 1,
  CreateGroupMessage_FieldNumber_SecretKey = 2,
};

@interface CreateGroupMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *identifier;

@property(nonatomic, readwrite, copy, null_resettable) NSString *secretKey;

@end

#pragma mark - ChatCookie

typedef GPB_ENUM(ChatCookie_FieldNumber) {
  ChatCookie_FieldNumber_Sign = 1,
  ChatCookie_FieldNumber_Data_p = 2,
};

@interface ChatCookie : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite, strong, null_resettable) ChatCookieData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Ack

typedef GPB_ENUM(Ack_FieldNumber) {
  Ack_FieldNumber_MsgId = 1,
  Ack_FieldNumber_Type = 2,
};

@interface Ack : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int32_t type;

@end

#pragma mark - OfflineMsgAck

typedef GPB_ENUM(OfflineMsgAck_FieldNumber) {
  OfflineMsgAck_FieldNumber_MsgIdsArray = 1,
};

@interface OfflineMsgAck : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *msgIdsArray;
/** The number of items in @c msgIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgIdsArray_Count;

@end

#pragma mark - ChatCookieData

typedef GPB_ENUM(ChatCookieData_FieldNumber) {
  ChatCookieData_FieldNumber_ChatPubKey = 1,
  ChatCookieData_FieldNumber_Salt = 2,
  ChatCookieData_FieldNumber_Expired = 3,
};

@interface ChatCookieData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *chatPubKey;

@property(nonatomic, readwrite, copy, null_resettable) NSData *salt;

@property(nonatomic, readwrite) int64_t expired;

@end

#pragma mark - MessageData

typedef GPB_ENUM(MessageData_FieldNumber) {
  MessageData_FieldNumber_ChatMsg = 1,
  MessageData_FieldNumber_ChatSession = 2,
};

/**
 * 传输层模型
 **/
@interface MessageData : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ChatMessage *chatMsg;
/** Test to see if @c chatMsg has been set. */
@property(nonatomic, readwrite) BOOL hasChatMsg;

@property(nonatomic, readwrite, strong, null_resettable) ChatSession *chatSession;
/** Test to see if @c chatSession has been set. */
@property(nonatomic, readwrite) BOOL hasChatSession;

@end

#pragma mark - ChatSession

typedef GPB_ENUM(ChatSession_FieldNumber) {
  ChatSession_FieldNumber_Salt = 1,
  ChatSession_FieldNumber_Ver = 2,
  ChatSession_FieldNumber_PubKey = 3,
};

/**
 * 临时协同密钥
 **/
@interface ChatSession : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *salt;

@property(nonatomic, readwrite, copy, null_resettable) NSData *ver;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pubKey;

@end

#pragma mark - ChatMessage

typedef GPB_ENUM(ChatMessage_FieldNumber) {
  ChatMessage_FieldNumber_MsgId = 1,
  ChatMessage_FieldNumber_MsgTime = 2,
  ChatMessage_FieldNumber_From = 3,
  ChatMessage_FieldNumber_To = 4,
  ChatMessage_FieldNumber_CipherData = 5,
  ChatMessage_FieldNumber_ChatType = 6,
  ChatMessage_FieldNumber_MsgType = 7,
  ChatMessage_FieldNumber_Ext = 8,
  ChatMessage_FieldNumber_SendStatus = 9,
};

/**
 * 消息体
 **/
@interface ChatMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@property(nonatomic, readwrite) int64_t msgTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, strong, null_resettable) GcmData *cipherData;
/** Test to see if @c cipherData has been set. */
@property(nonatomic, readwrite) BOOL hasCipherData;

@property(nonatomic, readwrite) ChatType chatType;

@property(nonatomic, readwrite) int32_t msgType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ext;

@property(nonatomic, readwrite) int32_t sendStatus;

@end

/**
 * Fetches the raw value of a @c ChatMessage's @c chatType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ChatMessage_ChatType_RawValue(ChatMessage *message);
/**
 * Sets the raw value of an @c ChatMessage's @c chatType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetChatMessage_ChatType_RawValue(ChatMessage *message, int32_t value);

#pragma mark - MessageUserInfo

typedef GPB_ENUM(MessageUserInfo_FieldNumber) {
  MessageUserInfo_FieldNumber_Uid = 1,
  MessageUserInfo_FieldNumber_Username = 2,
  MessageUserInfo_FieldNumber_Avatar = 3,
};

/**
 * 用户信息
 **/
@interface MessageUserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - TimeMessage

typedef GPB_ENUM(TimeMessage_FieldNumber) {
  TimeMessage_FieldNumber_Time = 1,
};

/**
 * 文本消息
 **/
@interface TimeMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *time;

@end

#pragma mark - TextMessage

typedef GPB_ENUM(TextMessage_FieldNumber) {
  TextMessage_FieldNumber_Content = 1,
  TextMessage_FieldNumber_AtUidsArray = 2,
  TextMessage_FieldNumber_SnapTime = 3,
};

/**
 * 文本消息
 **/
@interface TextMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *atUidsArray;
/** The number of items in @c atUidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger atUidsArray_Count;

@property(nonatomic, readwrite) int64_t snapTime;

@end

#pragma mark - EmotionMessage

typedef GPB_ENUM(EmotionMessage_FieldNumber) {
  EmotionMessage_FieldNumber_Content = 1,
  EmotionMessage_FieldNumber_SnapTime = 2,
};

/**
 * emoj表情
 **/
@interface EmotionMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) int64_t snapTime;

@end

#pragma mark - PhotoMessage

typedef GPB_ENUM(PhotoMessage_FieldNumber) {
  PhotoMessage_FieldNumber_URL = 1,
  PhotoMessage_FieldNumber_Thum = 2,
  PhotoMessage_FieldNumber_Size = 3,
  PhotoMessage_FieldNumber_ImageWidth = 4,
  PhotoMessage_FieldNumber_ImageHeight = 5,
  PhotoMessage_FieldNumber_SnapTime = 6,
};

/**
 * 图片消息
 **/
@interface PhotoMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *size;

@property(nonatomic, readwrite) int32_t imageWidth;

@property(nonatomic, readwrite) int32_t imageHeight;

@property(nonatomic, readwrite) int64_t snapTime;

@end

#pragma mark - VoiceMessage

typedef GPB_ENUM(VoiceMessage_FieldNumber) {
  VoiceMessage_FieldNumber_URL = 1,
  VoiceMessage_FieldNumber_TimeLength = 2,
  VoiceMessage_FieldNumber_SnapTime = 3,
};

/**
 * 音频消息
 **/
@interface VoiceMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t timeLength;

@property(nonatomic, readwrite) int64_t snapTime;

@end

#pragma mark - VideoMessage

typedef GPB_ENUM(VideoMessage_FieldNumber) {
  VideoMessage_FieldNumber_URL = 1,
  VideoMessage_FieldNumber_Cover = 2,
  VideoMessage_FieldNumber_TimeLength = 3,
  VideoMessage_FieldNumber_Size = 4,
  VideoMessage_FieldNumber_ImageWidth = 5,
  VideoMessage_FieldNumber_ImageHeight = 6,
  VideoMessage_FieldNumber_SnapTime = 7,
};

/**
 * 视频消息
 **/
@interface VideoMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cover;

@property(nonatomic, readwrite) int32_t timeLength;

@property(nonatomic, readwrite) int32_t size;

@property(nonatomic, readwrite) int32_t imageWidth;

@property(nonatomic, readwrite) int32_t imageHeight;

@property(nonatomic, readwrite) int64_t snapTime;

@end

#pragma mark - CardMessage

typedef GPB_ENUM(CardMessage_FieldNumber) {
  CardMessage_FieldNumber_Uid = 1,
  CardMessage_FieldNumber_Username = 2,
  CardMessage_FieldNumber_Avatar = 3,
};

/**
 * 名片消息
 **/
@interface CardMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - DestructMessage

typedef GPB_ENUM(DestructMessage_FieldNumber) {
  DestructMessage_FieldNumber_Time = 1,
};

/**
 * 开始阅后即焚
 **/
@interface DestructMessage : GPBMessage

@property(nonatomic, readwrite) int32_t time;

@end

#pragma mark - ReadReceiptMessage

typedef GPB_ENUM(ReadReceiptMessage_FieldNumber) {
  ReadReceiptMessage_FieldNumber_MessageId = 1,
};

/**
 * 阅后即焚已读消息
 **/
@interface ReadReceiptMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@end

#pragma mark - PaymentMessage

typedef GPB_ENUM(PaymentMessage_FieldNumber) {
  PaymentMessage_FieldNumber_PaymentType = 1,
  PaymentMessage_FieldNumber_HashId = 2,
  PaymentMessage_FieldNumber_Amount = 3,
  PaymentMessage_FieldNumber_MemberSize = 4,
  PaymentMessage_FieldNumber_Tips = 5,
};

/**
 * 收款消息
 **/
@interface PaymentMessage : GPBMessage

/** 0:单人收款 1:众筹 */
@property(nonatomic, readwrite) int32_t paymentType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int32_t memberSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - TransferMessage

typedef GPB_ENUM(TransferMessage_FieldNumber) {
  TransferMessage_FieldNumber_TransferType = 1,
  TransferMessage_FieldNumber_HashId = 2,
  TransferMessage_FieldNumber_Amount = 3,
  TransferMessage_FieldNumber_Tips = 4,
};

/**
 * 转账消息
 **/
@interface TransferMessage : GPBMessage

/** 0:单人转账 1:多人转账  2:外部转账 */
@property(nonatomic, readwrite) int32_t transferType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - LuckPacketMessage

typedef GPB_ENUM(LuckPacketMessage_FieldNumber) {
  LuckPacketMessage_FieldNumber_HashId = 1,
  LuckPacketMessage_FieldNumber_LuckyType = 2,
  LuckPacketMessage_FieldNumber_Tips = 3,
  LuckPacketMessage_FieldNumber_Amount = 4,
};

/**
 * 红包消息
 **/
@interface LuckPacketMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

/** 0:内部红包 1:外部红包 2:系统红包 */
@property(nonatomic, readwrite) int32_t luckyType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - LocationMessage

typedef GPB_ENUM(LocationMessage_FieldNumber) {
  LocationMessage_FieldNumber_Latitude = 1,
  LocationMessage_FieldNumber_Longitude = 2,
  LocationMessage_FieldNumber_Address = 3,
  LocationMessage_FieldNumber_ScreenShot = 4,
  LocationMessage_FieldNumber_ImageWidth = 5,
  LocationMessage_FieldNumber_ImageHeight = 6,
};

/**
 * 位置消息
 **/
@interface LocationMessage : GPBMessage

@property(nonatomic, readwrite) float latitude;

@property(nonatomic, readwrite) float longitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *screenShot;

@property(nonatomic, readwrite) int32_t imageWidth;

@property(nonatomic, readwrite) int32_t imageHeight;

@end

#pragma mark - NotifyMessage

typedef GPB_ENUM(NotifyMessage_FieldNumber) {
  NotifyMessage_FieldNumber_NotifyType = 1,
  NotifyMessage_FieldNumber_Content = 2,
  NotifyMessage_FieldNumber_Extion = 3,
};

/**
 * 提示消息
 **/
@interface NotifyMessage : GPBMessage

/** 红包 普通提醒 红包带详情（hashid） eg。。。。 */
@property(nonatomic, readwrite) int32_t notifyType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extion;

@end

#pragma mark - JoinGroupMessage

typedef GPB_ENUM(JoinGroupMessage_FieldNumber) {
  JoinGroupMessage_FieldNumber_Avatar = 1,
  JoinGroupMessage_FieldNumber_GroupName = 2,
  JoinGroupMessage_FieldNumber_GroupId = 3,
  JoinGroupMessage_FieldNumber_Token = 4,
};

/**
 * 加入群组消息
 **/
@interface JoinGroupMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - WebsiteMessage

typedef GPB_ENUM(WebsiteMessage_FieldNumber) {
  WebsiteMessage_FieldNumber_URL = 1,
  WebsiteMessage_FieldNumber_Title = 2,
  WebsiteMessage_FieldNumber_Subtitle = 3,
  WebsiteMessage_FieldNumber_Img = 4,
};

/**
 * 外部链接消息
 **/
@interface WebsiteMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subtitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *img;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
